const mongoose = require('mongoose')

//PasswordLog schema
const passwordLogSchema = new mongoose.Schema({
    userid:
	{
	    type: String, //Changed to string because API is using the owner's _id field generated by MongoDB to be used as the userid
		required: true
		//required: [true, "Please enter a userid"]
	},

    username:
    {
        type: String,
        required: false,
    }, 

    password:
    {
        type: String,
        required: true,
        //required: [true, "Please enter a password"]
    },

    application: // Password logs are searched by application
    {
        type: String,
        required: true,
    }
})

//Export the general model
const PasswordLog = mongoose.model("PasswordLog", passwordLogSchema); //Changed the name of the model to fit the mongoDB naming scheme
module.exports = PasswordLog;