const mongoose = require('mongoose')

//SecureNote schema
const secureNoteSchema = new mongoose.Schema({
    userid:
	{
	    type: String, //Changed to string because API is using the owner's _id field generated by MongoDB to be used as the userid
		required: true
		//required: [true, "Please enter a userid"]
	},

    title: // Notes are searched by title
    {
        type: String,
        required: true, //Changed to true because it is used in the serach
    }, 
   
    text:
    {
        type: String,
        required: true,
        //required: [true, "Please enter a note"]
    }
})

//Export the general model
const SecureNote = mongoose.model("SecureNote", secureNoteSchema); //Changed the name of the model to fit the mongoDB naming scheme
module.exports = SecureNote;