const mongoose = require('mongoose')

//UserLogin schema
const userCredSchema = new mongoose.Schema({ // userid removed because the user's _id field generated by MongoDB is being used in the API instead
    username:
    {
        type: String,
        required: false,
    }, 
   
    email:
    {
        type: String,
        required: true,
        //required: [true, "Please enter a email"]
    }, 

    password:
    {
        type: String,
        required: true,
        //required: [true, "Please enter a password"]
    },

    emailKey:
    {
        type: String,
        required: false,
    },
    
    resetKey:
    {
        type: String,
        required: false,
    },

    verified:
    {
        type: Boolean,
        required: true,
    }
})

//Export the general model
const User = mongoose.model("User", userCredSchema); //Changed the name of the model to fit the mongoDB naming scheme
module.exports = User;